using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using static Engine.GLFW;

namespace Engine
{
	public static class GL
	{
		static GL()
		{
			glClear = GetDelegate<Delegates.glClear>();
			glClearColor = GetDelegate<Delegates.glClearColor>();

			// Shaders
			glAttachShader = GetDelegate<Delegates.glAttachShader>();
			glBindBuffer = GetDelegate<Delegates.glBindBuffer>();
			glBindVertexArray = GetDelegate<Delegates.glBindVertexArray>();
			glCompileShader = GetDelegate<Delegates.glCompileShader>();
			glCreateProgram = GetDelegate<Delegates.glCreateProgram>();
			glCreateShader = GetDelegate<Delegates.glCreateShader>();
			glDeleteProgram = GetDelegate<Delegates.glDeleteProgram>();
			glDeleteShader = GetDelegate<Delegates.glDeleteShader>();
			glDeleteVertexArrays = GetDelegate<Delegates.glDeleteVertexArrays>();
			glGenVertexArrays = GetDelegate<Delegates.glGenVertexArrays>();
			glGetActiveUniform = GetDelegate<Delegates.glGetActiveUniform>();
			glGetProgramiv = GetDelegate<Delegates.glGetProgramiv>();
			glGetProgramInfoLog = GetDelegate<Delegates.glGetProgramInfoLog>();
			glGetShaderiv = GetDelegate<Delegates.glGetShaderiv>();
			glGetShaderInfoLog = GetDelegate<Delegates.glGetShaderInfoLog>();
			glGetUniformLocation = GetDelegate<Delegates.glGetUniformLocation>();
			glLinkProgram = GetDelegate<Delegates.glLinkProgram>();
			glShaderSource = GetDelegate<Delegates.glShaderSource>();
			glUseProgram = GetDelegate<Delegates.glUseProgram>();

			// Textures
			glBindTexture = GetDelegate<Delegates.glBindTexture>();
			glGenTextures = GetDelegate<Delegates.glGenTextures>();
			glTexImage2D = GetDelegate<Delegates.glTexImage2D>();
			glTexParameteri = GetDelegate<Delegates.glTexParameteri>();
		}

		#region Constants
		public const int GL_DEPTH_BUFFER_BIT = 0x00000100;
		public const int GL_STENCIL_BUFFER_BIT = 0x0000040;
		public const int GL_COLOR_BUFFER_BIT = 0x00004000;
		public const int GL_FALSE = 0;
		public const int GL_TRUE = 1;
		public const int GL_POINTS = 0x0000;
		public const int GL_LINES = 0x0001;
		public const int GL_LINE_LOOP = 0x0002;
		public const int GL_LINE_STRIP = 0x0003;
		public const int GL_TRIANGLES = 0x0004;
		public const int GL_TRIANGLE_STRIP = 0x0005;
		public const int GL_TRIANGLE_FAN = 0x0006;
		public const int GL_NEVER = 0x0200;
		public const int GL_LESS = 0x0201;
		public const int GL_EQUAL = 0x0202;
		public const int GL_LEQUAL = 0x0203;
		public const int GL_GREATER = 0x0204;
		public const int GL_NOTEQUAL = 0x0205;
		public const int GL_GEQUAL = 0x0206;
		public const int GL_ALWAYS = 0x0207;
		public const int GL_BLEND_EQUATION_RGB = 0x8009;
		public const int GL_VERTEX_ATTRIB_ARRAY_ENABLED = 0x8622;
		public const int GL_VERTEX_ATTRIB_ARRAY_SIZE = 0x8623;
		public const int GL_VERTEX_ATTRIB_ARRAY_STRIDE = 0x8624;
		public const int GL_VERTEX_ATTRIB_ARRAY_TYPE = 0x8625;
		public const int GL_CURRENT_VERTEX_ATTRIB = 0x8626;
		public const int GL_VERTEX_PROGRAM_POINT_SIZE = 0x8642;
		public const int GL_VERTEX_ATTRIB_ARRAY_POINTER = 0x8645;
		public const int GL_STENCIL_BACK_FUNC = 0x8800;
		public const int GL_STENCIL_BACK_FAIL = 0x8801;
		public const int GL_STENCIL_BACK_PASS_DEPTH_FAIL = 0x8802;
		public const int GL_STENCIL_BACK_PASS_DEPTH_PASS = 0x8803;
		public const int GL_MAX_DRAW_BUFFERS = 0x8824;
		public const int GL_DRAW_BUFFER0 = 0x8825;
		public const int GL_DRAW_BUFFER1 = 0x8826;
		public const int GL_DRAW_BUFFER2 = 0x8827;
		public const int GL_DRAW_BUFFER3 = 0x8828;
		public const int GL_DRAW_BUFFER4 = 0x8829;
		public const int GL_DRAW_BUFFER5 = 0x882A;
		public const int GL_DRAW_BUFFER6 = 0x882B;
		public const int GL_DRAW_BUFFER7 = 0x882C;
		public const int GL_DRAW_BUFFER8 = 0x882D;
		public const int GL_DRAW_BUFFER9 = 0x882E;
		public const int GL_DRAW_BUFFER10 = 0x882F;
		public const int GL_DRAW_BUFFER11 = 0x8830;
		public const int GL_DRAW_BUFFER12 = 0x8831;
		public const int GL_DRAW_BUFFER13 = 0x8832;
		public const int GL_DRAW_BUFFER14 = 0x8833;
		public const int GL_DRAW_BUFFER15 = 0x8834;
		public const int GL_BLEND_EQUATION_ALPHA = 0x883D;
		public const int GL_MAX_VERTEX_ATTRIBS = 0x8869;
		public const int GL_VERTEX_ATTRIB_ARRAY_NORMALIZED = 0x886A;
		public const int GL_MAX_TEXTURE_IMAGE_UNITS = 0x8872;
		public const int GL_FRAGMENT_SHADER = 0x8B30;
		public const int GL_GEOMETRY_SHADER = 0x8DD9;
		public const int GL_VERTEX_SHADER = 0x8B31;
		public const int GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = 0x8B49;
		public const int GL_MAX_VERTEX_UNIFORM_COMPONENTS = 0x8B4A;
		public const int GL_MAX_VARYING_FLOATS = 0x8B4B;
		public const int GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 0x8B4C;
		public const int GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 0x8B4D;
		public const int GL_SHADER_TYPE = 0x8B4F;
		public const int GL_FLOAT_VEC2 = 0x8B50;
		public const int GL_FLOAT_VEC3 = 0x8B51;
		public const int GL_FLOAT_VEC4 = 0x8B52;
		public const int GL_INT_VEC2 = 0x8B53;
		public const int GL_INT_VEC3 = 0x8B54;
		public const int GL_INT_VEC4 = 0x8B55;
		public const int GL_BOOL = 0x8B56;
		public const int GL_BOOL_VEC2 = 0x8B57;
		public const int GL_BOOL_VEC3 = 0x8B58;
		public const int GL_BOOL_VEC4 = 0x8B59;
		public const int GL_FLOAT_MAT2 = 0x8B5A;
		public const int GL_FLOAT_MAT3 = 0x8B5B;
		public const int GL_FLOAT_MAT4 = 0x8B5C;
		public const int GL_SAMPLER_1D = 0x8B5D;
		public const int GL_SAMPLER_2D = 0x8B5E;
		public const int GL_SAMPLER_3D = 0x8B5F;
		public const int GL_SAMPLER_CUBE = 0x8B60;
		public const int GL_SAMPLER_1D_SHADOW = 0x8B61;
		public const int GL_SAMPLER_2D_SHADOW = 0x8B62;
		public const int GL_DELETE_STATUS = 0x8B80;
		public const int GL_COMPILE_STATUS = 0x8B81;
		public const int GL_LINK_STATUS = 0x8B82;
		public const int GL_VALIDATE_STATUS = 0x8B83;
		public const int GL_INFO_LOG_LENGTH = 0x8B84;
		public const int GL_ATTACHED_SHADERS = 0x8B85;
		public const int GL_ACTIVE_UNIFORMS = 0x8B86;
		public const int GL_ACTIVE_UNIFORM_MAX_LENGTH = 0x8B87;
		public const int GL_SHADER_SOURCE_LENGTH = 0x8B88;
		public const int GL_ACTIVE_ATTRIBUTES = 0x8B89;
		public const int GL_ACTIVE_ATTRIBUTE_MAX_LENGTH = 0x8B8A;
		public const int GL_FRAGMENT_SHADER_DERIVATIVE_HINT = 0x8B8B;
		public const int GL_SHADING_LANGUAGE_VERSION = 0x8B8C;
		public const int GL_CURRENT_PROGRAM = 0x8B8D;
		public const int GL_POINT_SPRITE_COORD_ORIGIN = 0x8CA0;
		public const int GL_LOWER_LEFT = 0x8CA1;
		public const int GL_UPPER_LEFT = 0x8CA2;
		public const int GL_STENCIL_BACK_REF = 0x8CA3;
		public const int GL_STENCIL_BACK_VALUE_MASK = 0x8CA4;
		public const int GL_STENCIL_BACK_WRITEMASK = 0x8CA5;
		public const int GL_VERTEX_PROGRAM_TWO_SIDE = 0x8643;
		public const int GL_POINT_SPRITE = 0x8861;
		public const int GL_COORD_REPLACE = 0x8862;
		public const int GL_MAX_TEXTURE_COORDS = 0x8871;
		public const int GL_ZERO = 0;
		public const int GL_ONE = 1;
		public const int GL_SRC_COLOR = 0x0300;
		public const int GL_ONE_MINUS_SRC_COLOR = 0x0301;
		public const int GL_SRC_ALPHA = 0x0302;
		public const int GL_ONE_MINUS_SRC_ALPHA = 0x0303;
		public const int GL_DST_ALPHA = 0x0304;
		public const int GL_ONE_MINUS_DST_ALPHA = 0x0305;
		public const int GL_DST_COLOR = 0x0306;
		public const int GL_ONE_MINUS_DST_COLOR = 0x0307;
		public const int GL_SRC_ALPHA_SATURATE = 0x0308;
		public const int GL_FRONT = 0x0404;
		public const int GL_BACK = 0x0405;
		public const int GL_FRONT_AND_BACK = 0x0408;
		public const int GL_FOG = 0x0B60;
		public const int GL_LIGHTING = 0x0B50;
		public const int GL_TEXTURE_2D = 0x0DE1;
		public const int GL_CULL_FACE = 0x0B44;
		public const int GL_ALPHA_TEST = 0x0BC0;
		public const int GL_BLEND = 0x0BE2;
		public const int GL_COLOR_LOGIC_OP = 0x0BF2;
		public const int GL_DITHER = 0x0BD0;
		public const int GL_STENCIL_TEST = 0x0B90;
		public const int GL_DEPTH_TEST = 0x0B71;
		public const int GL_POINT_SMOOTH = 0x0B10;
		public const int GL_LINE_SMOOTH = 0x0B20;
		public const int GL_SCISSOR_TEST = 0x0C11;
		public const int GL_COLOR_MATERIAL = 0x0B57;
		public const int GL_NORMALIZE = 0x0BA1;
		public const int GL_RESCALE_NORMAL = 0x803A;
		public const int GL_POLYGON_OFFSET_FILL = 0x8037;
		public const int GL_VERTEX_ARRAY = 0x8074;
		public const int GL_NORMAL_ARRAY = 0x8075;
		public const int GL_COLOR_ARRAY = 0x8076;
		public const int GL_TEXTURE_COORD_ARRAY = 0x8078;
		public const int GL_MULTISAMPLE = 0x809D;
		public const int GL_SAMPLE_ALPHA_TO_COVERAGE = 0x809E;
		public const int GL_SAMPLE_ALPHA_TO_ONE = 0x809F;
		public const int GL_SAMPLE_COVERAGE = 0x80A0;
		public const int GL_NO_ERROR = 0;
		public const int GL_INVALID_ENUM = 0x0500;
		public const int GL_INVALID_VALUE = 0x0501;
		public const int GL_INVALID_OPERATION = 0x0502;
		public const int GL_STACK_OVERFLOW = 0x0503;
		public const int GL_STACK_UNDERFLOW = 0x0504;
		public const int GL_OUT_OF_MEMORY = 0x0505;
		public const int GL_EXP = 0x0800;
		public const int GL_EXP2 = 0x0801;
		public const int GL_FOG_DENSITY = 0x0B62;
		public const int GL_FOG_START = 0x0B63;
		public const int GL_FOG_END = 0x0B64;
		public const int GL_FOG_MODE = 0x0B65;
		public const int GL_FOG_COLOR = 0x0B66;
		public const int GL_CW = 0x0900;
		public const int GL_CCW = 0x0901;
		public const int GL_SMOOTH_POINT_SIZE_RANGE = 0x0B12;
		public const int GL_SMOOTH_LINE_WIDTH_RANGE = 0x0B22;
		public const int GL_ALIASED_POINT_SIZE_RANGE = 0x846D;
		public const int GL_ALIASED_LINE_WIDTH_RANGE = 0x846E;
		public const int GL_IMPLEMENTATION_COLOR_READ_TYPE_OES = 0x8B9A;
		public const int GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES = 0x8B9B;
		public const int GL_MAX_LIGHTS = 0x0D31;
		public const int GL_MAX_TEXTURE_SIZE = 0x0D33;
		public const int GL_MAX_MODELVIEW_STACK_DEPTH = 0x0D36;
		public const int GL_MAX_PROJECTION_STACK_DEPTH = 0x0D38;
		public const int GL_MAX_TEXTURE_STACK_DEPTH = 0x0D39;
		public const int GL_MAX_VIEWPORT_DIMS = 0x0D3A;
		public const int GL_MAX_ELEMENTS_VERTICES = 0x80E8;
		public const int GL_MAX_ELEMENTS_INDICES = 0x80E9;
		public const int GL_MAX_TEXTURE_UNITS = 0x84E2;
		public const int GL_NUM_COMPRESSED_TEXTURE_FORMATS = 0x86A2;
		public const int GL_COMPRESSED_TEXTURE_FORMATS = 0x86A3;
		public const int GL_SUBPIXEL_BITS = 0x0D50;
		public const int GL_RED_BITS = 0x0D52;
		public const int GL_GREEN_BITS = 0x0D53;
		public const int GL_BLUE_BITS = 0x0D54;
		public const int GL_ALPHA_BITS = 0x0D55;
		public const int GL_DEPTH_BITS = 0x0D56;
		public const int GL_STENCIL_BITS = 0x0D57;
		public const int GL_DONT_CARE = 0x1100;
		public const int GL_FASTEST = 0x1101;
		public const int GL_NICEST = 0x1102;
		public const int GL_PERSPECTIVE_CORRECTION_HINT = 0x0C50;
		public const int GL_POINT_SMOOTH_HINT = 0x0C51;
		public const int GL_LINE_SMOOTH_HINT = 0x0C52;
		public const int GL_POLYGON_SMOOTH_HINT = 0x0C53;
		public const int GL_FOG_HINT = 0x0C54;
		public const int GL_LIGHT_MODEL_AMBIENT = 0x0B53;
		public const int GL_LIGHT_MODEL_TWO_SIDE = 0x0B52;
		public const int GL_AMBIENT = 0x1200;
		public const int GL_DIFFUSE = 0x1201;
		public const int GL_SPECULAR = 0x1202;
		public const int GL_POSITION = 0x1203;
		public const int GL_SPOT_DIRECTION = 0x1204;
		public const int GL_SPOT_EXPONENT = 0x1205;
		public const int GL_SPOT_CUTOFF = 0x1206;
		public const int GL_CONSTANT_ATTENUATION = 0x1207;
		public const int GL_LINEAR_ATTENUATION = 0x1208;
		public const int GL_QUADRATIC_ATTENUATION = 0x1209;
		public const int GL_BYTE = 0x1400;
		public const int GL_UNSIGNED_BYTE = 0x1401;
		public const int GL_SHORT = 0x1402;
		public const int GL_UNSIGNED_SHORT = 0x1403;
		public const int GL_FLOAT = 0x1406;
		public const int GL_FIXED = 0x140C;
		public const int GL_CLEAR = 0x1500;
		public const int GL_AND = 0x1501;
		public const int GL_AND_REVERSE = 0x1502;
		public const int GL_COPY = 0x1503;
		public const int GL_AND_INVERTED = 0x1504;
		public const int GL_NOOP = 0x1505;
		public const int GL_XOR = 0x1506;
		public const int GL_OR = 0x1507;
		public const int GL_NOR = 0x1508;
		public const int GL_EQUIV = 0x1509;
		public const int GL_INVERT = 0x150A;
		public const int GL_OR_REVERSE = 0x150B;
		public const int GL_COPY_INVERTED = 0x150C;
		public const int GL_OR_INVERTED = 0x150D;
		public const int GL_NAND = 0x150E;
		public const int GL_SET = 0x150F;
		public const int GL_EMISSION = 0x1600;
		public const int GL_SHININESS = 0x1601;
		public const int GL_AMBIENT_AND_DIFFUSE = 0x1602;
		public const int GL_MODELVIEW = 0x1700;
		public const int GL_PROJECTION = 0x1701;
		public const int GL_TEXTURE = 0x1702;
		public const int GL_ALPHA = 0x1906;
		public const int GL_RGB = 0x1907;
		public const int GL_RGBA = 0x1908;
		public const int GL_LUMINANCE = 0x1909;
		public const int GL_LUMINANCE_ALPHA = 0x190A;
		public const int GL_UNPACK_ALIGNMENT = 0x0CF5;
		public const int GL_PACK_ALIGNMENT = 0x0D05;
		public const int GL_UNSIGNED_SHORT_4_4_4_4 = 0x8033;
		public const int GL_UNSIGNED_SHORT_5_5_5_1 = 0x8034;
		public const int GL_UNSIGNED_SHORT_5_6_5 = 0x8363;
		public const int GL_FLAT = 0x1D00;
		public const int GL_SMOOTH = 0x1D01;
		public const int GL_KEEP = 0x1E00;
		public const int GL_REPLACE = 0x1E01;
		public const int GL_INCR = 0x1E02;
		public const int GL_DECR = 0x1E03;
		public const int GL_VENDOR = 0x1F00;
		public const int GL_RENDERER = 0x1F01;
		public const int GL_VERSION = 0x1F02;
		public const int GL_EXTENSIONS = 0x1F03;
		public const int GL_MODULATE = 0x2100;
		public const int GL_DECAL = 0x2101;
		public const int GL_ADD = 0x0104;
		public const int GL_TEXTURE_ENV_MODE = 0x2200;
		public const int GL_TEXTURE_ENV_COLOR = 0x2201;
		public const int GL_TEXTURE_ENV = 0x2300;
		public const int GL_NEAREST = 0x2600;
		public const int GL_LINEAR = 0x2601;
		public const int GL_NEAREST_MIPMAP_NEAREST = 0x2700;
		public const int GL_LINEAR_MIPMAP_NEAREST = 0x2701;
		public const int GL_NEAREST_MIPMAP_LINEAR = 0x2702;
		public const int GL_LINEAR_MIPMAP_LINEAR = 0x2703;
		public const int GL_TEXTURE_MAG_FILTER = 0x2800;
		public const int GL_TEXTURE_MIN_FILTER = 0x2801;
		public const int GL_TEXTURE_WRAP_S = 0x2802;
		public const int GL_TEXTURE_WRAP_T = 0x2803;
		public const int GL_TEXTURE0 = 0x84C0;
		public const int GL_TEXTURE1 = 0x84C1;
		public const int GL_TEXTURE2 = 0x84C2;
		public const int GL_TEXTURE3 = 0x84C3;
		public const int GL_TEXTURE4 = 0x84C4;
		public const int GL_TEXTURE5 = 0x84C5;
		public const int GL_TEXTURE6 = 0x84C6;
		public const int GL_TEXTURE7 = 0x84C7;
		public const int GL_TEXTURE8 = 0x84C8;
		public const int GL_TEXTURE9 = 0x84C9;
		public const int GL_TEXTURE10 = 0x84CA;
		public const int GL_TEXTURE11 = 0x84CB;
		public const int GL_TEXTURE12 = 0x84CC;
		public const int GL_TEXTURE13 = 0x84CD;
		public const int GL_TEXTURE14 = 0x84CE;
		public const int GL_TEXTURE15 = 0x84CF;
		public const int GL_TEXTURE16 = 0x84D0;
		public const int GL_TEXTURE17 = 0x84D1;
		public const int GL_TEXTURE18 = 0x84D2;
		public const int GL_TEXTURE19 = 0x84D3;
		public const int GL_TEXTURE20 = 0x84D4;
		public const int GL_TEXTURE21 = 0x84D5;
		public const int GL_TEXTURE22 = 0x84D6;
		public const int GL_TEXTURE23 = 0x84D7;
		public const int GL_TEXTURE24 = 0x84D8;
		public const int GL_TEXTURE25 = 0x84D9;
		public const int GL_TEXTURE26 = 0x84DA;
		public const int GL_TEXTURE27 = 0x84DB;
		public const int GL_TEXTURE28 = 0x84DC;
		public const int GL_TEXTURE29 = 0x84DD;
		public const int GL_TEXTURE30 = 0x84DE;
		public const int GL_TEXTURE31 = 0x84DF;
		public const int GL_REPEAT = 0x2901;
		public const int GL_CLAMP_TO_EDGE = 0x812F;
		public const int GL_PALETTE4_RGB8_OES = 0x8B90;
		public const int GL_PALETTE4_RGBA8_OES = 0x8B91;
		public const int GL_PALETTE4_R5_G6_B5_OES = 0x8B92;
		public const int GL_PALETTE4_RGBA4_OES = 0x8B93;
		public const int GL_PALETTE4_RGB5_A1_OES = 0x8B94;
		public const int GL_PALETTE8_RGB8_OES = 0x8B95;
		public const int GL_PALETTE8_RGBA8_OES = 0x8B96;
		public const int GL_PALETTE8_R5_G6_B5_OES = 0x8B97;
		public const int GL_PALETTE8_RGBA4_OES = 0x8B98;
		public const int GL_PALETTE8_RGB5_A1_OES = 0x8B99;
		public const int GL_LIGHT0 = 0x4000;
		public const int GL_LIGHT1 = 0x4001;
		public const int GL_LIGHT2 = 0x4002;
		public const int GL_LIGHT3 = 0x4003;
		public const int GL_LIGHT4 = 0x4004;
		public const int GL_LIGHT5 = 0x4005;
		public const int GL_LIGHT6 = 0x4006;
		public const int GL_LIGHT7 = 0x4007;
		#endregion

		public static Delegates.glClear glClear;
		public static Delegates.glClearColor glClearColor;

		// Shaders
		public static Delegates.glAttachShader glAttachShader;
		public static Delegates.glBindBuffer glBindBuffer;
		public static Delegates.glBindVertexArray glBindVertexArray;
		public static Delegates.glCompileShader glCompileShader;
		public static Delegates.glCreateProgram glCreateProgram;
		public static Delegates.glCreateShader glCreateShader;
		public static Delegates.glDeleteProgram glDeleteProgram;
		public static Delegates.glDeleteShader glDeleteShader;
		public static Delegates.glDeleteVertexArrays glDeleteVertexArrays;
		public static Delegates.glGenVertexArrays glGenVertexArrays;
		public static Delegates.glGetActiveUniform glGetActiveUniform;
		public static Delegates.glGetProgramiv glGetProgramiv;
		public static Delegates.glGetProgramInfoLog glGetProgramInfoLog;
		public static Delegates.glGetShaderiv glGetShaderiv;
		public static Delegates.glGetShaderInfoLog glGetShaderInfoLog;
		public static Delegates.glGetUniformLocation glGetUniformLocation;
		public static Delegates.glLinkProgram glLinkProgram;
		public static Delegates.glShaderSource glShaderSource;
		public static Delegates.glUseProgram glUseProgram;

		// Textures
		public static Delegates.glBindTexture glBindTexture;
		public static Delegates.glGenTextures glGenTextures;
		public static Delegates.glTexImage2D glTexImage2D;
		public static Delegates.glTexParameteri glTexParameteri;

		private static T GetDelegate<T>() where T : class
		{
			Type type = typeof(T);

			// See https://stackoverflow.com/a/35321707/7281613.
			return Marshal.GetDelegateForFunctionPointer(glfwGetProcAddress(type.Name), type) as T;
		}

		public static unsafe class Delegates
		{
			public delegate void glClear(uint mask);
			public delegate void glClearColor(float red, float green, float blue, float alpha);

			// Shaders
			public delegate void glAttachShader(uint program, uint shader);
			public delegate void glBindBuffer(uint target, uint buffer);
			public delegate void glBindVertexArray(uint array);
			public delegate void glCompileShader(uint shader);
			public delegate uint glCreateProgram();
			public delegate uint glCreateShader(uint shaderType);
			public delegate void glDeleteProgram(uint program);
			public delegate void glDeleteShader(uint shader);
			public delegate void glDeleteVertexArrays(uint n, uint* arrays);
			public delegate void glGenVertexArrays(uint n, uint* arrays);
			public delegate void glGetActiveUniform(uint program, uint index, uint bufSize, uint* length, int* size,
				uint* type, char* name);
			public delegate void glGetProgramiv(uint program, uint pname, int* @params);
			public delegate void glGetProgramInfoLog(uint program, uint maxLength, uint* length, char* infoLog);
			public delegate void glGetShaderiv(uint shader, uint pname, int* @params);
			public delegate void glGetShaderInfoLog(uint shader, uint maxLength, uint* length, char* infoLog);
			public delegate int glGetUniformLocation(uint program, char* name);
			public delegate void glLinkProgram(uint program);
			public delegate void glShaderSource(uint shader, uint count, char* @string, int* length);
			public delegate void glUseProgram(uint program);

			// Textures
			public delegate void glBindTexture(uint target, uint texture);
			public delegate void glGenTextures(uint n, uint* textures);
			public delegate void glTexImage2D(uint target, int level, int internalformat, uint width, uint height,
				int border, uint format, uint type, void* data);
			public delegate void glTexParameteri(uint target, uint pname, int param);
		}
	}
}
